version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
  producer:
    image: buharovalexander/microservices-demo-producer
    ports:
      - 8080:8080
    environment:
      KAFKA_HOSTNAME: kafka
      KAFKA_PORT: 9092
    depends_on:
    - kafka
  consumer:
    image: buharovalexander/microservices-demo-consumer
    environment:
      KAFKA_HOSTNAME: kafka
      KAFKA_PORT: 9092
      MONGO_HOSTNAME: mongodb
      MONGO_PORT: 27017
    depends_on:
    - kafka
    - mongodb